### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by majid701** [shrikanth7698/ChatView#2]
First of all great library absolutely amazing work. 
I have noticed that sometimes my app gets this null pointer exception. It only happens some of the time could be related to the fact that everytime there is a change in my datasource I call clearMessages() on the chat view and draw all messages again.

Any suggestions on how to fix?

**Stacktrace**:
`04-26 13:59:08.744 852-852/checkd.com.fieldapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: checkd.com.fieldapp, PID: 852
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.shrikanthravi.chatview.data.Message.getType()' on a null object reference
        at com.shrikanthravi.chatview.data.MessageAdapter.getItemViewType(MessageAdapter.java:106)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5820)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)`

**Comment by shrikanth7698** [comment]
for every message you add you should set the data type of that message.
In stack trace, you can see that message.getype is null. you didn't set the message type.
